### ISSUE TITLE
Binary releases for i586 / Geode anyone ?

### ISSUE THREAD

**Issue by rhy-ama** [DNSCrypt/dnscrypt-proxy#1075]

**Comment by jedisct1** [comment]
There has been a recent thread on the OpenBSD mailing-list about Golang packages and their compatibility with Soekris boxes. Check it out.
I guess the latest i386 packages for OpenBSD-current should now work on it.

**Comment by rhy-ama** [comment]
@jedisct1 ```openbsd-i386``` binary produces ```Segmentation fault``` and ```linux-i386``` gives ```Illegal instruction``` 

I cant compile given instructions listed in the wiki - the tooling is outdated and/or inproperly linked for debian jessie distribution im using on these #580

**Comment by jedisct1** [comment]
Since you didn’t look for it https://marc.info/?t=157376595300001&r=1&w=2

**Comment by rhy-ama** [comment]
@jedisct1 Arrogant assumption. I've found and read it. It does not resolve the issue i've described

**Comment by jedisct1** [comment]
There are other discussions about that topic, converging towards the same solution https://www.google.com/search?q=golang+amd+geode&ie=UTF-8&oe=UTF-8&hl=en-us&client=safari

If that doesn’t work for you, you should contribute to these and help them figure out why. At least OpenBSD packages are now supposed to work on Geode CPUs, so if this is not the case, your input will definitely be useful.

**Comment by rhy-ama** [comment]
[Go version go1.13.4 linux/386 built with appropriate flags to support AMD Geode processors (lack of SSE instruction vs typical i386 go compilation)](https://github.com/rhy-ama/Geode-linux-go)

[Geode specific build of dnscrypt-proxy 2.0.34-beta1](https://github.com/rhy-ama/Geode-linux-dnscrypt-proxy)
